# Generated by Django 5.0.1 on 2024-01-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_comment_client_comments_todolist_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client_name'},
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'deactive'), ('aktif', 'non-aktif')], default='active', max_length=255),
        ),
    ]
